config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('recipe/', include('recipe.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    home_view,
    about_view,
    contact_view,
    terms_view,
)

app_name = 'core'

# Path: core/urls.py
urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('terms/', terms_view, name='terms'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# View for the home page
def home_view(request):
    return render(request, 'core/home.html')

# View for the about page
def about_view(request):
    return render(request, 'core/about.html')

# View for the contact page
def contact_view(request):
    return render(request, 'core/contact.html')

# View for the terms page
def terms_view(request):
    return render(request, 'core/terms.html')

# View for the 404 page
def handler404(request, exception):
    return render(request, 'core/404.html', status=404)

# View for the 500 page
def handler500(request):
    return render(request, 'core/500.html', status=500)

core/templates/core/about.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="Flavor Fusion">
    <meta property="og:description" content="About flavor fusion">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'core:about' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="Flavor fusion">
    <meta name="twitter:title" content="Flavor fusion">
    <meta name="twitter:description" content="About flavor fusion">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'core:about' %}">
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">
    
    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="Opaque Maniac">
    <meta name="description" content="about flavor fusion">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/about.css' %}">
{% endblock css %}
{% block title %}About{% endblock %}
{% block content %}
<!-- Template for the about page -->

    <section class="section about__section">
        <h2 class="section__title">Our Culinary Story</h2>
        <article class="section__article">
            <p class="section__text">
                Welcome to FlavorFushion, where our culinary journey unfolds into a tapestry 
                of flavors and shared moments. Our story is one of passion, experimentation, 
                and a shared love for bringing people together through the joy of cooking. 
                Founded by Aisha Foster, our platform is more than just a collection of 
                recipes; it's a testament to the belief that a well-cooked meal has the power 
                to create lasting memories. As avid food enthusiasts, we invite you to delve 
                into our kitchen adventures, learn about our inspirations, and discover the 
                heart behind each recipe. Join us on this flavorful exploration as we turn 
                ordinary ingredients into extraordinary dishes. This is our culinary story - 
                a celebration of the love and creativity that food brings to our lives.
            </p>
    </section>
    <section class="section founders__section">
        <h2 class="section__title">Founders</h2>
        <article class="section__article">
            <h3 class="founder__name">A Journey Through Flavor with <span class="name">Aisha Foster</span></h3>
            <div class="founder__detail color-primary">
                <img class="section__img normal-img" src="{% static 'core/img/founder-two.jpg' %}" alt="Aisha Foster">
                <p class="section__text">
                    Meet Aisha Foster, the heart and soul behind FlavorFushion. Aisha's culinary tale 
                    unfolds with a passion deeply rooted in her family's kitchen traditions, where love 
                    and creativity were essential ingredients. From her early days experimenting with simple 
                    desserts to crafting intricate dishes inspired by diverse cultures, Aisha's kitchen is a 
                    canvas of culinary expression. Drawn by a desire to share her culinary discoveries, Aisha 
                    founded FlavorFushion. Through her platform, Aisha invites you to join her on a gastronomic 
                    adventure, where every recipe tells a unique story and each meal becomes a celebration of flavors. 
                    Embrace the spirit of Aisha Foster's culinary journey and discover the joy of cooking that she 
                    brings to every dish. Welcome to the world of FlavorFushion, where Aisha's love for food becomes 
                    a shared experience for all.
                </p>
            </div>
        </article>
        <article class="section__article">
            <h3 class="founder__name">The Culinary Odyssey of <span class="name">Malik Thompson</span></h3>
            <div class="founder__detail color-secondary">
                <img class="section__img alternate-img" src="{% static 'core/img/founder-one.jpg' %}" alt="Malik Thompson">
                <p class="section__text alternate-text">
                Meet Malik Thompson, the creative force behind FlavorFushion. Malik's culinary 
                journey began with a childhood steeped in the rich aromas of his grandmother's 
                kitchen. Inspired by these flavorful memories, Malik developed a passion for 
                turning ordinary ingredients into extraordinary dishes. From perfecting family 
                recipes to experimenting with global cuisines, Malik's kitchen became a haven for 
                culinary exploration. One day, after crafting a show-stopping fusion dish, Malik 
                envisioned a platform where he could share his love for cooking with a wider audience. 
                And so, FlavorFushion was born. Join Malik on this flavorful adventure, where every recipe 
                is a chapter in his culinary story, and each dish is a masterpiece waiting to be savored.
                </p>
            </div>
        </article>
        <article class="section__article atlernate">
            <h3 class="founder__name">Unveiling Flavorful Chapters with <span class="name">Marcus Bennett</span></h3>
            <div class="founder__detail color-primary">
                <img class="section__img normal-img" src="{% static 'core/img/founder-three.jpg' %}" alt="Marcus Bennet">
                <p class="section__text alternate-text">
                    Embark on a culinary voyage with Marcus Bennett, the creative mind behind FlavorFushion. 
                    Marcus's gastronomic journey traces back to the warmth of family kitchens, where the art of 
                    cooking became a form of self-expression. From mastering classic recipes to fearlessly 
                    experimenting with innovative flavors, Marcus's kitchen is a haven for culinary exploration. 
                    Motivated by a desire to inspire others, Marcus founded FlavorFushion, inviting 
                    you to step into his world of enticing aromas and delectable tastes. Join Marcus on a flavorful 
                    expedition, where each recipe is a chapter in his culinary story, and every dish is an invitation 
                    to savor the beauty of diverse cuisines. Immerse yourself in the world of Marcus Bennett, and let 
                    the joy of cooking become your own.
                </p>
            </div>
        </article>
        <article class="section__article">
            <h3 class="founder__name">Crafting Culinary Harmony with <span class="name">Nia Reynolds</span></h3>
            <div class="founder__detail color-secondary">
                <img class="section__img alternate-img" src="{% static 'core/img/founder-four.jpg' %}" alt="Nia Reynolds">
                <p class="section__text">
                    Discover the culinary world through the eyes of Nia Reynolds, the driving force behind FlavorFushion. 
                    Nia's culinary narrative is woven with threads of tradition, innovation, and a deep-rooted passion for 
                    the art of cooking. From learning cherished family recipes to infusing her dishes with contemporary 
                    flair, Nia's kitchen is a canvas of culinary harmony. With a vision to share the joy of cooking, Nia 
                    established FlavorFushion, inviting you to partake in her flavorful journey. Join Nia as she unravels 
                    the secrets behind each recipe, turning ordinary moments into extraordinary culinary experiences. Indulge 
                    in the diverse and delightful world curated by Nia Reynolds, where every dish tells a story, and the pleasure 
                    of sharing good food becomes a universal language. Welcome to a kitchen where Nia's culinary expertise 
                    becomes an inspiration for all who savor the beauty of a well-cooked meal.
                </p>
            </div>
        </article>
    </section>
{% endblock content %}
{% block js %}
{% endblock js %}

core/templates/core/home.html
{% extends "base.html" %}{% load static %}
{% block meta %}
<!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
<meta property="og:title" content="Flavor Fusion">
<meta property="og:description" content="Flavor fusion, one stop for all recipes">
<meta property="og:type" content="website">
<meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'core:home' %}">
<meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
<meta property="og:image:width" content="900">
<meta property="og:image:height" content="900">

<!-- Twitter Card Meta Tags -->
<meta name="twitter:card" content="Flavor Fusion">
<meta name="twitter:title" content="Flavor fusion">
<meta name="twitter:description" content="Flavor fusion, one stop for all recipes">
<meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'core:home' %}">
<meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
<meta name="twitter:image:width" content="900">
<meta name="twitter:image:height" content="900">

<!-- Additional Meta Tags (optional) -->
<meta name="author" content="Opaque Maniac">
<meta name="description" content="flavor fusion, website to get any recipe you need">
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/home.css' %}">
{% endblock css %}
{% block title %}Home{% endblock %}
{% block content %}
<!-- The home page -->

<section class="section section__intro">
    <h2 class="intro__title">Welcome to culinary heaven</h2>
    <div class="intro__container">
        <img class="intro__image" src="{% static 'core/img/home-intro-img.jpg' %}" alt="bowl of ramen">
        <p class="into__paragraph">
            Welcome to FlavorFushion, where culinary inspiration meets simplicity! Our passion for delicious and diverse
            flavors is reflected in every recipe we curate. Whether you're a seasoned chef or a kitchen novice, our goal
            is to make cooking an enjoyable experience for everyone. Explore a world of mouthwatering recipes, culinary
            tips, and easy-to-follow instructions that will elevate your home-cooked meals. Join us on a culinary
            journey that celebrates the joy of good food, shared with those you love. Let's turn your kitchen into a
            place of creativity and delectable memories!
        </p>
    </div>
</section>
<section class="section section__info transparent">
    <h2 class="info__title">About us</h2>
    <div class="info__container">
        <img class="info__image" src="{% static 'core/img/about-image.jpg' %}" alt="a family cooking">
        <p class="info__text">
            At FlavorFushion, our story is as flavorful as the recipes we share. Founded with a shared love for cooking
            and a belief in the power of a well-cooked meal to bring people together, our platform is a celebration of
            culinary
            exploration. What started as a personal journey through kitchen experiments has evolved into a vibrant
            community where
            food enthusiasts, both seasoned chefs and kitchen newcomers, come together. Our mission is simple: to
            inspire and
            simplify your cooking experience. Join us as we share our culinary adventures, tips, and a collection of
            recipes that
            have become cherished favorites. At FlavorFushion, we believe that a shared meal is not just a moment in
            time but a memory in the making. Welcome to our kitchen; we're thrilled to have you here!
        </p>
    </div>
</section>
<section class="section section__call">
    <h2 class="call__title">Start Your Culinary Adventure Today!</h2>
    <div class="call__container">
        <img class="call__image" id="last" src="{% static 'core/img/call-image-2.jpg' %}"
            alt="a beautiful spread for dinner">
        <p class="call__text">
            Are you ready to embark on a journey of delightful flavors and culinary creativity? Dive into our collection
            of
            mouthwatering recipes that cater to every taste and skill level. Whether you're a seasoned chef or a kitchen
            novice,
            there's something here for everyone. Join us in making cooking an enjoyable and rewarding experience. Click
            below to
            explore our recipes, discover kitchen tips, and transform your meals from ordinary to extraordinary. Let the
            culinary
            adventure begin - start cooking with passion and purpose today!
        </p>
    </div>
</section>
{% endblock content %}
{% block js %}
{% endblock js %}

core/templates/core/terms.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="Terms And Conditions Flavor Fusion">
    <meta property="og:description" content="Terms and conditions when using flavor fusion">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'core:terms' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="Terms and Conditions Flavor Fusion">
    <meta name="twitter:title" content="Terms and Conditions Flavor fusion">
    <meta name="twitter:description" content="Terms and conditions when using flavor fusion">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'core:terms' %}">
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">

    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="Opaque Maniac">
    <meta name="description" content="terms and conditions when using the flavor fusion platform">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/terms.css' %}">
{% endblock css %}
{% block title %}Terms & conditions{% endblock %}
{% block content %}
<!-- Template for terms and conditions -->

<section class="section">
    <h2>Terms & conditions</h2>
    <h3>By accessing and using this website, you agree to abide by these fictional terms and conditions.</h3>
    <ol class="terms-list">
        <li>All characters and events mentioned on this website are purely fictional and do not represent real
            individuals or occurrences.</li>
        <li>The content on this website is for entertainment purposes only and should not be considered as professional
            advice.</li>
        <li>Any resemblance to actual persons, living or dead, or actual events is purely coincidental.</li>
        <li>We reserve the right to change, modify, or discontinue any feature or aspect of this website at any time.
        </li>
        <li>Users are prohibited from attempting to reverse engineer, hack, or otherwise interfere with the website's
            functionality.</li>
        <li>This website may use cookies for a better user experience; however, these cookies are entirely fictional and
            have no actual functionality.</li>
        <li>The website owner is not responsible for any loss, injury, or inconvenience caused by the use of this
            website.</li>
        <li>Users are encouraged to use this website responsibly and respect the privacy of others.</li>
        <li>All intellectual property, including but not limited to text, images, and logos, is the property of the
            website owner.</li>
        <li>Any user-generated content submitted to the website becomes the property of the website owner.</li>
        <li>We do not guarantee the accuracy, completeness, or timeliness of any information on this website.</li>
        <li>Users are responsible for keeping their account information secure and confidential.</li>
        <li>The website owner reserves the right to suspend or terminate user accounts for any reason.</li>
        <li>Users are prohibited from engaging in any unlawful or harmful activities on this website.
        <li>This website may contain links to external websites; however, we do not endorse or take responsibility for
            the content of those sites.</li>
        <li>Users may contact the website owner for fictional support, but we do not guarantee a response or resolution.
        </li>
        <li>These terms and conditions are subject to change without notice.</li>
        <li>By continuing to use this website, you acknowledge that you have read and understood these fictional terms
            and conditions.</li>
    </ol>
</section>
{% endblock content %}
{% block js %}
{% endblock js %}